fluid-dev/hexo-theme-fluid

README.md, _config.yml, layout/_partial/comments/valine.ejs, layout/_partial/head.ejs
添加了 Valine 评论系统。
**未经测试，不保证无 bug。**
=> Add Valine comment system

_config.yml, layout/_partial/footer.ejs, layout/_partial/nav.ejs, layout/about.ejs, layout/archive.ejs, layout/index.ejs, layout/layout.ejs, layout/post.ejs, source/css/about.css, source/css/index.css, source/css/main.css, source/css/post.css
1. 移动端的两侧间距减小，以增加单屏更多的内容
2. 分离不同页面的 CSS
3. 面板居中使用自适应
4. 配置增加自定义博客名称，可和title设置不同的文本
5. 略微调整首页列表样式
=>  优化移动端样式及部分调整

layout/_partial/analytics.ejs, layout/_partial/head.ejs, layout/_partial/toc.ejs, layout/post.ejs, source/css/post.css
- 文章主体的左偏移 -1，toc 宽度 +1
- 调整 toc 字体大小和缩进
=> 调整文章页和 toc 样式

layout/_partial/comments/gitalk.ejs
=> fix issues 91

source/css/_pages/_about/about.styl
Fix avatar display problem of `about` page in #166
=> :bug: 修复about页面头像会根据原始图片大小不一致而发生变化的问题

layout/_partial/postjs.ejs
makes tons of output in console
=> 🐛 purge console output

source/css/_pages/_post/post.styl
=> :bug: 修复样式不生效问题

scripts/tags/checkbox.js, source/css/_pages/_post/tags.styl
=> :art: Tag 插件支持复选框

_static_prefix.yml, layout/_partial/comments/gitalk.ejs
修复gitalk模块md5函数未定义导致模块加载异常的bug
=> 🐛 修复gitalk评论模块

languages/en.yml, languages/ja.yml, languages/zh-CN.yml, layout/post.ejs
Fixes #250 
支持post中上下篇切换标识的多语言
=> 支持post中上下篇切换标识的多语言

.eslintrc, .github/workflows/lint.yaml
=> :art:更新lint规则和action

source/css/_pages/_base/rewrite.styl
=> :art: 修改分页样式

_config.yml, layout/_partial/comments/remark42.ejs, source/css/_pages/_base/rewrite.styl, source/js/color-schema.js
添加对 [Remark42](https://remark42.com/) 评论系统的支持。
支持暗色模式皮肤切换。
=> 添加对 Remark42 评论系统的支持

languages/de.yml
=> German language support

_config.yml, layout/_partial/comments/waline.ejs
添加一款从 Valine衍生的带后端评论系统，支持LeanCloud，MongoDB，MySQL等多种数据存储方式。
其它功能详见：https://waline.js.org/
=> ✨ 增加 waline 评论插件

layout/_partial/comments/remark42.ejs
=> fix remark42 load

layout/categories.ejs
=> fix: category breakdown has posts and subcats

layout/_partial/comments/remark42.ejs
如果直接使用`comments`，会报错
> Remark42: Can't find root node.
=> 修复remark42报错：Remark42: Can't find root node.

_config.yml, layout/_partial/comments/cusdis.ejs, source/js/color-schema.js
=> ✨ support cusdis comment plugin

layout/_partial/comments/twikoo.ejs
Closes imaegoo/twikoo#171
@leicancun 请帮助测试此改动是否有效
=> 🐛 修复 Twikoo 评论加载参数错误

layout/_partial/plugins/local-search.ejs
=> fix: solve the problem of unavailable search.

layout/_partial/comments/twikoo.ejs, layout/_partial/comments/valine.ejs, layout/_partial/comments/waline.ejs, source/js/color-schema.js, source/js/plugins.js, source/js/utils.js
评论系统的图片不能点击放大，主题本身自带 fancybox，所以想在评论系统中引用 fancybox 提供评论图片点击放大功能。
=> 为评论图片添加 fancybox 支持（以 Twikoo 为例）

_config.yml
=> :sparkles: 升级 Waline 到 1.3.4 增加统计功能，自带随主题黑暗模式

layout/_partial/plugins/math.ejs
=> fix: mathjax regex match

languages/es.yml
=> 🌐 多语言添加西班牙语 (Spanish)

layout/_partials/plugins/analytics.ejs
=> 🐛 修复统计代码语法错误

_config.yml, layout/_partials/comments/giscus.ejs
=> :sparkles: 支持 giscus 评论插件

layout/404.ejs
=> bux fix: fix 404 redirect path

source/js/color-schema.js
:bug: 修复切换light和dark时，手机浏览器的theme-color颜色未正确变化的问题
=> :bug: 修复切换light和dark时，手机浏览器的theme-color颜色未正确变化的问题

scripts/helpers/wordcount.js
=> 区分方块字和单词的 wordcount 计数方法

source/js/color-schema.js
=> 🐛 修复Giscus背景不透明

source/js/events.js
=> 🐛 修复永远加载不完的进度条 #1067

source/js/umami-view.js
=> 修复不能正确获取Umami统计信息的问题

_config.yml, layout/_partials/comments/disqus.ejs
允许用户指定 api, admin, adminLabel 参数，支持填入多个 apikey
https://github.com/fluid-dev/hexo-theme-fluid/issues/838
=> 完善 DisqusJS 评论系统
