- source/js/post.js
Hi，很好看的主题。背景图真滴好看✔
我用的时候发现toc的位置不能随浏览器的缩放一起运动，从下面两个截图能看到这个bug。当浏览器从全屏变为窗口模式时，甚至不能看到toc。
所以我解除了toc的左侧坐标限制，让它跟随自己的容器运动就好
> fix toc's malpostion during resizing

- languages/ja.yml
`About` 我翻译成了 `本ブログ情報`，意为`本博客的信息`。因为该主题用于`hexo博客`，而且`About`有"关于~"的意思。
> 菜单名添加多语言 日语

- layout/index.ejs
- layout/post.ejs
bugs fix for [issues149](https://github.com/fluid-dev/hexo-theme-fluid/issues/149)。当使用`category_map`和`tag_map`后，categories和tags的通过直接拼接得到的url不对，使用`url_for`函数来查找正确的url。
> modify link addr for categories and tags

- scripts/lazyload.js
img tag 如果包含回行无法匹配，导致loading图片不显示
> lazyload 匹配img正则修复

- source/js/lazyload.js
> remove unnecessary event listening

- layout/_partial/plugins/math.ejs
it seems that when using the default `CommonHTML` as output will cause strange math display for `mathjax` on chrome and edge.
May be we can change default to  `HTML-CSS` and use `NativeMML` for IE with MathPlayer support.
before:
after:
> Fix a math display error on Chrome/Egge

- layout/_partial/plugins/analytics.ejs
Tencent Analytics will always be included and loaded no matter you set 
```
tencent:  
sid:  SOME SID
cid:
```
or not.
Since `theme.web_analytics.tencent` have child key `theme.web_analytics.tencent.sid` and not setting `theme.web_analytics.tencent.sid` means that the Tencent Analytics should not be included. 
We should always check `theme.web_analytics.tencent.sid` here.
> fix a bug that Tencent Analytics is always included

- source/js/local-search.js
在使用本地搜索功能时，关键词无法明显的显示，因此在js中主动增加样式使它高亮
> 增加搜索时关键词高亮 (暂不支持自定义配置)

- layout/_partial/comments/disqus.ejs
修改变量 disqus_config 的声明位置。
当将 disqus_config 放在 loadDisqus() 内时，this 的指代的是 loadDisqus() 函数，故会出现 Disqus 无法正确加载的问题。
另外使用 <%= page.permalink %> 代替 <%= config.url %>/<%= page.path %>
> 修复 disqus 加载失败

- layout/_partial/comments/waline.ejs
看了下原作者的文件，meta和requiredFields字段的值是一样的，但是requiredFields加了转义后输出，这样配置后会报 Unexpected token ‘&’ 错误，所以改了下和meta保持一致了
> waline文件requiredFields字段转义后报错问题

- layout/_partial/head.ejs
- layout/index.ejs
- 由用户指定文章页面的description
- 文章节选默认获取文章的description属性
修改前：
---
修改后：
原版：
- 优：无需额外在MD中设置属性；更加方便简洁；通常情况下也能较好的表述文章的大致内容，节省用户额外概括的时间。
- 劣： 对于长话开篇的情况，单纯的内容截取可能无法完全的表达文章的具体内容；可能将大标题也截入，无标点的情况下影响句子的通畅性。  
改版： 
- 优：可以完全的表达文章的大致内容（取决于用户的概括能力）；看上去更简洁精炼。
- 劣：额外的MD属性，可能影响代码的简洁性；需要使用者自行概括。
该项修改无论是对于博主亦或是访客都无直观上的变化，仅出现在源代码中。  
**但是**对于搜索引擎的收录是有好处的。虽然不是直接对SEO的优化，但是对description 的指定将改变诸如百度，谷歌等搜索引擎对文章内容的摘录，从而使访问者在搜索引擎搜索时能够更明确的文章的大致内容，从而增加访客量。
原版：
对标题的摘录影响句子的通畅性。
---
改版：
就我个人而言，我觉得这样的额外配置是很有必要的。虽然博主可能需要花额外的时间，但方便了用户的阅读，避免了无用的点击也增加了针对的点击。
其实我个人认为，原版的文章截取更类似于以前的 内容截取—展开全文 的逻辑；而修改后则是侧重于文章内容的概括：更针对用户的阅读体验。  
不可避免的不同人肯定有不同的侧重方向，所以预想的改动是额外在config配置文件中添加相应的选项供博主自行抉择。然而我并不确定您是否有添加该功能的意向，也就暂时先做到这一步了。
> 由用户指定页面的description

- _config.yml
- layout/_partial/comments/waline.ejs
- package.json
waline新增anonymous配置项。  
根据官方文档，anonymous默认值为：` `  
而`layout/_partial/comments/waline.ejs`中渲染代码如下：
```
anonymous: <%= theme.waline.anonymous %>,
```
当anonymous为默认值时，渲染为空，导致渲染出的js代码`Uncaught SyntaxError: Unexpected token ','`异常。
> 修复waline加载失败，并更新waline静态资源

- layout/links.ejs
请求不到头像时本应该显示设置的默认的头像，
但是在1.8.9中无法显示，是srcset的问题，看源码是设置为null，
因此修改把srcset删掉！！
修改后可以显示默认头像。
> 修改1.8.9版本中请求不到头像时显示不了默认头像的问题

- package.json
Fluid主题源码中使用了ejs和stylus，如果博客主工程里没有添加相应的renderer插件的话就会渲染异常。考虑到用户之前使用的主题未必使用ejs、stylus，因此可能会没有安装相应的renderer插件，因此增加peerDependencies以在安装时提示用户。
另外，local-search功能中也依赖了nunjucks库，因此同样添加到peerDependencies中（相关issue：#475）。
> 🔧 增加必要的peer dependencies

- layout/_partial/head.ejs
Add Open Graph to the head to support Twitter Card.
It would be like the below screenshot. I hope you guys like that.
Feel free to close PR if it isn't needed.
Refs:
- https://hexo.io/docs/helpers.html#open-graph
- https://cards-dev.twitter.com/validator
> feature: Add Open Graph to the head

- source/css/_pages/_post/tag_plugin.styl
实现 #558 
重新计算颜色并调整 alpha 替代 tag plugin 相关的 `background-color`。 在 light mode 和 dark mode 均有不错效果。
顺便也修改了 inline label 的效果。
> feat: add dark mode support for tag and label plugin

- scripts/helpers/scope.js
It was written originally like
```js
case 'categories' || 'category':
return page.layout === 'categories' || page.layout === 'category';
```
However, ('categories' || 'category') is equal to 'categories'(`js short-circuit evaluation`).
so category will not take effect. 😄
> fix wrong switch-case conditions in scope.js

- source/css/_pages/_post/highlight.styl
在 Tag 中的代码块，下方行间距异常。
{% note success %}
```
Something
```
{% endnote %}
[这是我的 Blog 的一个例子](https://potat0.cc/posts/20220726/Register_DN42_Domain/#%E4%BF%AE%E6%94%B9named-conf-options)
> 修复 Tag 中的代码块下方行间距异常

- layout/404.ejs
#855 丢失了引号？成了光杆司令
```
Uncaught SyntaxError: Invalid regular expression: missing /
```
> 🐛 再次修复 404 页面路径

- scripts/generators/local-search.js
- scripts/helpers/export-config.js
- source/js/local-search.js
1. 像 #912 里描述的一样，`searchConfig.content || true` 导致`content`设置永远为`true`
2. [local-search.js](https://github.com/fluid-dev/hexo-theme-fluid/compare/master...wuhao21:hexo-theme-fluid:master#diff-873e111eabba35a687c63ed2717d8ab4ce96cf1c3a1f9ec09e2bfdd001b2b6e8) 优化了搜索：如果内容为空就跳过。但是假如`searchConfig.content` 为 `false`，那么内容就永远为空
1. 改为 `searchConfig.content && true`，对应注释里的“默认为True”
2.  Export `searchConfig.content`到后端，然后确保只有在`include_content_in_search`开启的时候才做这个优化。
- Before
- After
另外自动format了一下 scripts/helpers/export-config.js 如果要用之前的style请随意修改:)
> 修复`search.content`无法使用的BUG #912

- scripts/filters/post-filter.js
- scripts/generators/index-generator.js
- scripts/generators/pages.js
这里是 issue https://github.com/fluid-dev/hexo-theme-fluid/issues/864 的pull request。
写作过程中，我们常常遇见由于内容过多导致某个主题变成系列文章的情况，往往一个系列还包含5篇以上的文章，如果全部罗列在首页显然不是一个优雅的做法。
私以为一个优雅的解决办法是为系列文章创建一个索引 post，在启用 category_bar 的同时为索引 post 中添加同系列每篇文章的url，首页上只展示每个系列的索引 post 即可。为此，我重写并覆盖了 hexo 的 hexo-generator-index 插件（说是重写也就是做了几处修改），同时在 post_fliter 处将主页文章这一分类过滤出来。
考虑到兼容性，archive 默认关闭，不影响原有 post 渲染。
>  为 post 的 Front-matter 中添加 archive 选项用于决定 post 是否在首页展示（默认仍为展示）

- _config.yml
- layout/_partials/plugins/analytics.ejs
Universal Analytics (UA) will stop processing data on July 1, 2023 (July 1, 2024 for Analytics 360 properties).
Google has officially merged the tracking ID and gtag ID. This RP integrates the two parts of tracking ID and gtag ID into MEASUREMENT ID
> Migrate Google tracking from UA to GA4

- scripts/events/lib/footnote.js
- scripts/tags/note.js
增加脚注对中文和字母的支持。
```markdown
脚注[^可中文可汉字可数字]
[^可中文可汉字可数字]: 脚注 增加支持中文、字母、数字混搭
```
> 脚注 增加支持中文、字母、数字混搭

- source/css/_pages/_index/index.styl
fix https://github.com/fluid-dev/hexo-theme-fluid/issues/991
> :bug: 修复首页空白摘要在移动端仍然占位

- _config.yml
- scripts/tags/fold.js
- source/css/_pages/_base/color-schema.styl
- source/css/_pages/_post/post-tag.styl
- source/css/_variables/base.styl
这是 #992 的 PR。
有些很长的参考内容，需要在文章中折叠起来，以便让读者有更好的阅读体验。
视频：https://github.com/AimTao/hexo-theme-fluid/blob/example/example.mp4
在行文过程中，增加标签。
```markdown
{% fold "折叠块的标题"%}
折叠内容，例如图片、代码块、文本等各类元素。
{% endfold %}
```
> feat:增加折叠块功能 resolve #992

- source/js/color-schema.js
这个问题分两个方面：
首先，评论区的iframe加载比较慢，导致这行代码：
[`var giscus = document.querySelector('iframe.giscus-frame');`](https://github.com/fluid-dev/hexo-theme-fluid/blob/9eefc8f24b42fbc9c430144bb059a655ae91d5e3/source/js/color-schema.js#L242)
`giscus` 始终返回 `null`，后续代码没有运行
其次，即便能正常运行，如果设置了黑色主题，评论区iframe会显示白色背景，这是个[已知BUG](https://github.com/giscus/giscus/issues/675)，看着很割裂：
合并PR的代码之后恢复正常：
> 修正giscus主题设置问题

- _config.yml
- layout/_partials/plugins/analytics.ejs
> Add Umami Analytics configuration

- _config.yml
Breaking changes https://github.com/bryanbraun/anchorjs/releases/tag/5.0.0
修改原因：https://github.com/bryanbraun/anchorjs/issues/188#issuecomment-1382674984
`touch` 在 anchorjs 5.0.0 版本后被移除。visibility 设置的 `touch` 选项被移除，现在只有 `hover` 和 `always` 两个可选项
使用 `touch` 的站点会回退到 `hover` 的行为
> Update _config.yml with anchor.js version 5.0.0

- layout/_partials/comments/disqus.ejs
If disqusjs is disabled:
https://github.com/fluid-dev/hexo-theme-fluid/blob/0f49caf39dc05eff9e2ea4d77d3b7f73ec1d9423/layout/_partials/comments/disqus.ejs#L18-L20
but if disqusjs is enabled, url and identifier is not specified(develop branch):
https://github.com/fluid-dev/hexo-theme-fluid/blob/b6865956e047c878cc5c80cef7774e9d1c14b824/layout/_partials/comments/disqus.ejs#L9-L15
As result, when I visit `example.com/a-post` has comments, but `example.com/a-post?v=t` has no comment.
**For disqusjs, url and identifier should keep same.**
> fix disqusjs url,identifier
